### ISSUE TITLE
Build mme doesn't work

### ISSUE THREAD

**Issue by JorgeVBZ** [OPENAIRINTERFACE/openair-mme#10]
Hi, I'am trying to install the OAI EPC on Ubuntu 18.04.5 LTE VirtualBox Virtual Machine (VM) with 4 cores and 4 GB RAM. 
The installation of the HSS is correct.
When I execute the _./build_mme -i_ command it gets frozen  like you can see in the below image.

![mme](https://user-images.githubusercontent.com/62287692/93454896-e8792080-f8db-11ea-8310-fdeaaed869ce.png)

Moreover, the SPGW fails too like you can see in the below image.

![spgw](https://user-images.githubusercontent.com/62287692/93454907-eca53e00-f8db-11ea-9fee-77ba4e7b5020.png)

Why it doesn't work? Is the execution on VM a problem? Please help me to find a solution, I need to implement a virtual 4G Network as soon as possible.

Thanks in advance,

Regards.

**Comment by matthew-william-lock** [comment]
Hi Jorge!

I am quite new to OAI myself but have you tried running this line first:
```
./build_mme --check-installed-software --force 
```

This is following the tutorial provided [here](https://www.youtube.com/watch?v=HT1upWeJMGA)

**Comment by JorgeVBZ** [comment]
Omg... I forgot add the options that you write...
Writing that command it works fine! :D

Thanks!
