### ISSUE TITLE
Failed to set virtual interfaces

### ISSUE THREAD

**Issue by matthew-william-lock** [OPENAIRINTERFACE/openair-mme#12]
https://github.com/OPENAIRINTERFACE/openair-mme/blob/75bc0993613f61072342f5ae13dca28574253671/scripts/run_mme#L207

This method is not defined and the following error is returned when runnnig run_mme script:
```
./run_mme: line 207: set_cn_virtual_interfaces: command not found

```

**Comment by JorgeVBZ** [comment]
Hi my friends,

I have the solution. Please change the content of your openair-mme/build/tools/builder_help file for the content of the attached file.

[build_helper.txt](https://github.com/OPENAIRINTERFACE/openair-mme/files/5268733/build_helper.txt)

Now you can close this issue my friend.

Regards!
